# frontend/Dockerfile.dev
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire frontend source code
COPY . .

# Expose port 5173
EXPOSE 5173

# Command to run the application
CMD ["npm", "run", "dev"]