networks:
  UpsDevs:
    driver: bridge

services:
  database:
    image: ghcr.io/upsdev42069/upsdev-database:latest
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    restart: unless-stopped
    networks:
      - UpsDevs
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    image: ghcr.io/upsdev42069/upsdev-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    networks:
      - UpsDevs
    volumes:
      - db-data:/app/data
      - ./backend/migrations:/app/migrations
    restart: unless-stopped
    command: ["/app/main"]

  frontend:
    image: ghcr.io/upsdev42069/upsdev-frontend:latest
    build: ./frontend
    ports:
      - "8069:8069"
    environment:
      - VITE_API_URL=https://whonose.dk/api
    networks:
      - UpsDevs
    depends_on:
      - backend
    restart: unless-stopped

  proxy:
    image: ghcr.io/upsdev42069/upsdev-proxy:latest
    build:
      context: ./tls
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./tls/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/whonose.dk:/etc/letsencrypt/live/whonose.dk
      - /etc/letsencrypt/archive/whonose.dk:/etc/letsencrypt/archive/whonose.dk
    networks:
      - UpsDevs
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  db-data:
