services:
  database:
    image: ghcr.io/upsdev42069/upsdev-database:latest
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./database/.env
    restart: always

  backend:
    image: ghcr.io/upsdev42069/upsdev-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - database
    networks:
      - UpsDevs
    restart: unless-stopped

  frontend:
    image: ghcr.io/upsdev42069/upsdev-frontend:latest
    ports:
      - "8069:8069"
    environment:
      - VITE_API_URL=http://backend:8080/api
    depends_on:
      - backend
    networks:
      - UpsDevs
    restart: unless-stopped

  proxy:
    image: ghcr.io/upsdev42069/upsdev-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - UpsDevs
    restart: always

networks:
  UpsDevs:
    driver: bridge
