# docker-compose.dev.yml
networks:
  UpsDevs:
    driver: bridge

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./backend/migrations:/app/migrations
    env_file:
      - ./database/.env
    restart: unless-stopped
    networks:
      - UpsDevs
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/vendor
      - ./backend/migrations:/app/migrations
    networks:
      - UpsDevs
    depends_on:
      - database
    command: ["air"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - UpsDevs
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host"]

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - UpsDevs
  #   depends_on:
  #     - backend

volumes:
  database:
