# docker-compose.dev.yml
networks:
  UpsDevs:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/vendor
    networks:
      - UpsDevs
    command: ["air"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - UpsDevs
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host"]
