global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "go_backend"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: ["backend:8080"] # Update if running on a different host or port
