# Use the official Golang image as the base image
FROM golang:1.23.1-alpine

# Install necessary dependencies for CGO and SQLite
RUN apk add --no-cache git

# Set the Current Working Directory inside the container
WORKDIR /app

# Install air for live reloading
RUN go install github.com/air-verse/air@latest

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code from the current directory to the Working Directory inside the container
COPY . .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable with air
CMD ["air"]